-- CreateEnum
CREATE TYPE "EWhenToAlert" AS ENUM ('URL_BECOMES_UNAVAILABLE', 'URL_DOES_NOT_CONTAIN_KEYWORD', 'URL_CONTAINS_A_KEYWORD', 'URL_RETURNS_HTTP_STATUS_OTHER_THAN', 'HOST_DOES_NOT_RESPOND_TO_PING');

-- CreateEnum
CREATE TYPE "ENextAction" AS ENUM ('DO_NOTHING', 'IMMEDIATELY_ALERT_ALL_OTHER_TEAM_MEMBER', 'WITHIN_3_MINUTES_ALERT_ALL_OTHER_TEAM_MEMBERS', 'WITHIN_5_MINUTES_ALERT_ALL_OTHER_TEAM_MEMBERS', 'WITHIN_10_MINUTES_ALERT_ALL_OTHER_TEAM_MEMBERS');

-- AlterTable
ALTER TABLE "monitors" ADD COLUMN     "actionsAfterIncident" TEXT[],
ADD COLUMN     "nextAction" "ENextAction" NOT NULL DEFAULT 'WITHIN_3_MINUTES_ALERT_ALL_OTHER_TEAM_MEMBERS',
ADD COLUMN     "whenToAlert" "EWhenToAlert" NOT NULL DEFAULT 'URL_BECOMES_UNAVAILABLE',
ALTER COLUMN "status" SET DEFAULT 200,
ALTER COLUMN "downtime" SET DEFAULT 0;
