/*
  Warnings:

  - The values [USER,ADMIN,SUPER_ADMIN] on the enum `ERole` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "ERole_new" AS ENUM ('CEO', 'CTO', 'CIO', 'COO', 'CFO', 'SRE', 'SOFTWARE_ENGINEER', 'SENIOR_SOFTWARE_ENGINEER', 'LEAD_ENGINEER', 'ENGINEERING_MANAGER', 'DEVOPS_ENGINEER', 'QA_ENGINEER', 'SDET', 'SYSTEMS_ARCHITECT', 'UI_ENGINEER', 'BACKEND_ENGINEER', 'FRONTEND_ENGINEER', 'PRODUCT_MANAGER', 'PRODUCT_OWNER', 'UX_DESIGNER', 'UIUX_DESIGNER', 'BUSINESS_ANALYST', 'GRAPHIC_DESIGNER', 'INTERACTION_DESIGNER', 'VISUAL_DESIGNER', 'MARKETING_MANAGER', 'SALES_MANAGER', 'CUSTOMER_SUCCESS_MANAGER', 'ACCOUNT_EXECUTIVE', 'IT_SUPPORT', 'SYSTEM_ADMINISTRATOR', 'NETWORK_ADMINISTRATOR', 'OPERATIONS_MANAGER', 'HR_MANAGER', 'RECRUITER', 'FINANCIAL_ANALYST', 'ACCOUNTANT', 'EXECUTIVE_ASSISTANT', 'OFFICE_MANAGER', 'LEGAL_COUNSEL', 'COMPLIANCE_OFFICER');
ALTER TABLE "users" ALTER COLUMN "role" DROP DEFAULT;
ALTER TABLE "users" ALTER COLUMN "role" TYPE "ERole_new" USING ("role"::text::"ERole_new");
ALTER TYPE "ERole" RENAME TO "ERole_old";
ALTER TYPE "ERole_new" RENAME TO "ERole";
DROP TYPE "ERole_old";
ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 'SRE';
COMMIT;

-- AlterTable
ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 'SRE';
